### ISSUE TITLE
Error when loading with AutoGenes.load

### ISSUE THREAD

**Issue by greynolds81** [theislab/AutoGeneS#1]
Hi,

I've been having difficulties reloading ag pickle files after generating them. I've been trying to follow the "SaveLoadTest.ipynb" notebook but have the same error message each time. I'm not quite sure what's going wrong.
Thanks very much!

```
import numpy as np
import pandas as pd
import sys
import importlib
import pickle
from autogenes import AutoGenes

import os.path

%load_ext autoreload
%autoreload 1
%aimport autogenes

importlib.reload(autogenes)

ag = AutoGenes.load('ag.pickle')


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-412bf52ad40b> in <module>
      1 os.chdir('/home/ngr18/hcaskin/theis_decon')
----> 2 healthy_ag = AutoGenes.load('eczema_ag.pickle')

~/.local/lib/python3.6/site-packages/autogenes/core.py in load(file)
    300 
    301   def load(file):
--> 302     return pickle.load(open(file, 'rb'))
    303 
    304   #

~/anaconda3/envs/hcaskin/lib/python3.6/site-packages/dill/_dill.py in load(file, ignore, **kwds)
    268 def load(file, ignore=None, **kwds):
    269     """unpickle an object from a file"""
--> 270     return Unpickler(file, ignore=ignore, **kwds).load()
    271 
    272 def loads(str, ignore=None, **kwds):

~/anaconda3/envs/hcaskin/lib/python3.6/site-packages/dill/_dill.py in load(self)
    470 
    471     def load(self): #NOTE: if settings change, need to update attributes
--> 472         obj = StockUnpickler.load(self)
    473         if type(obj).__module__ == getattr(_main_module, '__name__', '__main__'):
    474             if not self._ignore:

~/anaconda3/envs/hcaskin/lib/python3.6/site-packages/dill/_dill.py in find_class(self, module, name)
    460             return type(None) #XXX: special case: NoneType missing
    461         if module == 'dill.dill': module = 'dill._dill'
--> 462         return StockUnpickler.find_class(self, module, name)
    463 
    464     def __init__(self, *args, **kwds):

AttributeError: Can't get attribute 'IndividualGA' on <module 'deap.creator' from '/home/ngr18/anaconda3/envs/hcaskin/lib/python3.6/site-packages/deap/creator.py'>

```

Versions
deap 1.3.1; python 3.6.9; cachetools 4.0.0; dill 0.3.1.1

**Comment by lila167** [comment]
Hi @greynolds81. I tested pickle on the example [here](https://github.com/theislab/AutoGeneS/blob/master/deconv_example/bulkDeconvolution_using_singleCellReferenceProfiles.ipynb) following the instructions in this [notebook](https://github.com/theislab/AutoGeneS/blob/master/jupyter/SaveLoadTest.ipynb) and it works for me. So after ```ag.run(..)```, I did ```ag.save('saved_ag.pickle')``` and after calling ```ag2 = AutoGenes.load('saved_ag.pickle') ```, ag2 was similar to ag. Have you saved ```ag.pickle``` already in your code?

**Comment by maxims94** [comment]
Thank you for bringing this to our attention. This probably occurs because some of the classes are created dynamically and don't exist until AutoGenes is run at least once. I will figure out a fix.

**Comment by maxims94** [comment]
Pushed a patch. You should now be able to run `SaveLoadTest.ipynb` to generate an `saved_ag.pickle` and then load it with `LoadTest.ipynb` which is analogous to your code.
