### ISSUE TITLE
Data structure - how to obtain the signature matrix?

### ISSUE THREAD

**Issue by miketerkelsen** [theislab/AutoGeneS#11]
Hi, 

So starting on a good note, very nice tool you've provided here! However, after having run through it I'm struggling a bit with the data structure. Let's say I've run the modules within autogenes and have obtained my cell proportions. How can i export the signature matrix? Is it saved within the autogenes object or would I've remake it in another way?

Best 
Mike

**Comment by lila167** [comment]
Hi Mike, 

thanks for your interest. The function "init" returns the mean expressions when you use single cell data as input. When you call "select", it returns a list of genes. You can then filter the mean expressions using those genes. Did it help?

Best,
Hana
