### ISSUE TITLE
where is the 'GSE75748_sc_cell_type_ec.csv'?

### ISSUE THREAD

**Issue by woshiyangsi** [theislab/AutoGeneS#12]
Dear authors,
          Thanks for your excellent work .
          I have a question that how can i download the file 'GSE75748_sc_cell_type_ec.csv''?
        https://github.com/theislab/AutoGeneS/blob/master/deconv_example/bulkDeconvolution_using_singleCellReferenceProfiles.ipynb
In [2]:
#read single-cell data
file = './data/GSE75748_sc_cell_type_ec.csv'
adata = sc.read(file, cache=True).transpose()
adata

Looking forward your reply,
Siyu

**Comment by lila167** [comment]
Hi,

Thanks for using our tool!!
You can download the single cell data from: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE75748

Best,
Hana

**Comment by woshiyangsi** [comment]
Hi,Hana

Thank you for your quick reply.
I want to  build a single cell input data such as 'GSE75748_sc_cell_type_ec.csv'.And i use this command:
>>>adata.T.to_df().to_csv('matrix.csv')

Is the resulting expression matrix the same CPM as your test data(GSE75748_sc_cell_type_ec.csv)

Looking forward your reply.
Siyu

**Comment by lila167** [comment]
Hi Siyu,

If you are reading the raw counts (the values in your matrix.csv are integers), you need to normalize (scanpy.pp.normalize) the data after filtering out the low quality genes in your single-cell data as well as the genes that don't appear in your bulk data.

Best,
Hana
