### ISSUE TITLE
Normalization of cell type proportions

### ISSUE THREAD

**Issue by PelzKo** [theislab/AutoGeneS#13]
When using autogenes, the output of the deconvolve function can contain negative numbers. Now I found the method `def normalize_proportions(data,copy):` in your example at https://github.com/theislab/AutoGeneS/blob/master/deconv_example/bulkDeconvolution_using_singleCellReferenceProfiles.ipynb, but since there is no other mention how to convert the output to cell type proportions which add up to one in the documentation or the paper, I was wondering whether that is the recommended way to do it.
Another possibilities would be `normalize <- function(x) {
return ((x - min(x)) / (max(x) - min(x)))
}` and then scale it to one, which would not create as many zero proportion cell types as the method normalize_proportions.

What would be your recommended way of converting the output of deconvolve() to cell type proportions that add up to one for each sample?

**Comment by lila167** [comment]
Thanks for using our tool. Using svr for inferring cell type proportions can result in negative values. One needs to set negative values to zero and then scale the rest to sum up to one. 
If you use nnls, the proportions will be positive (but might also be larger than one) and you can normalize them as you suggested.

Hope this helps.
Hana

**Comment by PelzKo** [comment]
Thanks
