### ISSUE TITLE
Error occurs in ag.init step

### ISSUE THREAD

**Issue by ShaowenJ** [theislab/AutoGeneS#14]
Hi, 
I was trying my first time AutoGeneS on a public dataset after running without error following the tutorial.
But an error occurs in the ag.init step.
Here is my code:

```{python}
adata_norm = sc.pp.normalize_per_cell(coh1_adata, copy=True)
adata_log = sc.pp.log1p(adata_norm,copy=True)
sc.pp.highly_variable_genes(adata_log, flavor = "seurat_v3", n_top_genes=4000)
adata_proc = adata_norm[:, adata_log.var[adata_log.var['highly_variable']==True].index]
# I assume the matrix is just the average expression matrix of celltypes
res = pd.DataFrame(columns=adata_proc.var_names, index=adata_proc.obs['new_celltype'].cat.categories)
for x in adata_proc.obs.new_celltype.cat.categories:
    res.loc[x]=adata_proc[adata_proc.obs['new_celltype'].isin([x]),:].X.mean(0)

centroids_sc_hv = res.T
centroids_sc_hv.shape
ag.init(centroids_sc_hv.T)
```

And the error is :
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1304110/259709457.py in <module>
----> 1 ag.init(res)
      2 ag.optimize(ngen=5000,seed=0,nfeatures=400,mode='fixed',offspring_size=100,verbose=True)

~/miniconda3/lib/python3.9/site-packages/autogenes/interface.py in init(self, data, celltype_key, genes_key, use_highly_variable, **kwargs)
     86       self.data = data.values
     87       self.data_genes = data.columns.values
---> 88       self.main = AutoGeneS(self.data)
     89       self.pre_selection = np.full((data.shape[1],),True)
     90 

~/miniconda3/lib/python3.9/site-packages/autogenes/core.py in __init__(self, data)
     40       raise ValueError("Number of columns (genes) must be >= number of rows (cell types)")
     41 
---> 42     if not np.isfinite(self.data).all():
     43       raise ValueError("Some entries in data are not scalars")
     44 

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Do you know how to fix it and what caused it?

Thanks!

**Comment by lila167** [comment]
Hi,

Thanks for your interest in our tool.

The errors are quite informative:

```ValueError("Number of columns (genes) must be >= number of rows (cell types)")``` means that you should have more genes than cell types, otherwise the problem is not identifiable. Make sure that your are feeding the right matrix. Maybe you need to transpose the matrix.

Please also make sure that all the entries in your matrix is scaler, so there is no "None" for example: ``` ValueError("Some entries in data are not scalars")```

Best.

**Comment by ShaowenJ** [comment]
Thanks for the quick reply.
Yep, it turns out is the type of my df, it is not float.
Thanks
