### ISSUE TITLE
Reference matrix (scRNAseq)

### ISSUE THREAD

**Issue by Diennguyen8290** [theislab/AutoGeneS#15]
Many thanks for developing such a great tool.

I have one question regarding the reference matrix using scRNAseq data: is it required to use healthy tissue - derived data? 
To my understanding, the purpose of using reference matrix is to have a database of cell types that are thought to be present in the tissue of interest, but wondering about the abovementioned matter. For example, my RNAseq data to do the cellular deconvolution is derived from chronic hepatitis B, in which I expected to have hepatocyte populations with different fibrotic states and there is no way to estimate these populations using a normal human liver - derived scRNAseq dataset as a reference matrix. Is is ok to use a reference matrix from a scRNAseq dataset of livers with different fibrosis degrees?

Many thanks,
Dien

**Comment by lila167** [comment]
Hi Dien,

Thanks for using our tool!!
Yes, of course. You should select your reference dataset (scRNA-seq) as close as possible to your bulk samples. If the populations with different fibrotic states are distinct enough and the model can find the differentiating genes across them, you can use their signatures for deconvolution. However if some of those states are highly similar, you might need to merge them. I recommend you to check Figure 5 in our paper: https://www.sciencedirect.com/science/article/pii/S2405471221001927

Best,
Hana

**Comment by Diennguyen8290** [comment]
Many thanks, Hana.

Regards,
Dien
