### ISSUE TITLE
Can AutoGeneS utilise MicroArray data also?

### ISSUE THREAD

**Issue by ce-we** [theislab/AutoGeneS#20]
Hi

Thank you very much for this tool!

I was wondering if the tool can only be used to deconvolve bulk RNA-seq data or if you can also use it to deconvolve MicroArray data? Have you done any testing on MicroArray data?

Best regards, Clara

**Comment by lila167** [comment]
Hi Clara, thanks for considering our tool!
Yes, we have tested that on MicroArray in here:
https://onlinelibrary.wiley.com/doi/full/10.1111/all.15152

Best,
Hana
