### ISSUE TITLE
Recommendation for max.iter parameter

### ISSUE THREAD

**Issue by alex-d13** [theislab/AutoGeneS#21]
Hi,

Thanks for the nice tool :)

I am having some issues with autogenes, where sometimes the process will not finish ( even after 5 days) on the same dataset on which it previously finished in less than 1h. I believe that this might be due to the number of iterations and that the algorithm does not terminate due to some reason. If i set the `max.iter` parameter to something other than -1 (the default), this issue did not appear anymore.
My question now would be, what value would be a reasonable choice here? I think it can actually be quite high but just to have this limit that autogenes can terminate in every circumstance.

Best,
Alex

**Comment by lila167** [comment]
Hi, 
I'm very sorry for my late response.
Often I set max.iter to 5K for 4-5K highly variable genes.
