### ISSUE TITLE
Definition of matrix in deconvolution based on formula

### ISSUE THREAD

**Issue by TashaTu** [theislab/AutoGeneS#22]
Hi,
Thanks for your useful tool!
I am wondering where I can find **Matrix S** which is a k × k diagonal matrix mentioned in your paper methods.
Besides, I am not sure what "**average number of mRNAs in cell type l (also called cell size)**" means. 
Is the value of matrix S merge an average number of mRNAs in all of the genes in 1 cell type?  

Best,
Tasha

**Comment by lila167** [comment]
Hi Tasha,

Thanks for your interest.
K refers to the number of cell types. So, it should be the average number of mRNAs across cells within each cell type.
