### ISSUE TITLE
normalization of gene expression data

### ISSUE THREAD

**Issue by soueryw** [theislab/AutoGeneS#23]
Hi, 

Do the scRNA and bulk data inputted into autogeneS both need to be normalized using the same approach? I can't tell based on the documentation. 

Thanks so much in advance.

**Comment by lila167** [comment]
Hi,

We recommend to filter the low quality genes before normalization and normalize both sc and bulk on the same set of genes. However, the normalization technique can vary and depends on the bulk protocol.
