### ISSUE TITLE
Could you make it possible to pass different Nu and C values?

### ISSUE THREAD

**Issue by nik1sto** [theislab/AutoGeneS#5]
https://github.com/theislab/AutoGeneS/blob/5627144286c0ba8e49d83f0bfd88ea6815ff6da7/autogenes/interface.py#L268

**Comment by lila167** [comment]
@nik1sto Thanks for bringing that up. I will fix that. However, you should be able to pass the function (model) as input to the deconvolution function.

**Comment by giovp** [comment]
any update on this @lila167 ? Thank you!

**Comment by giovp** [comment]
@lila167 would be important to have this for the project. Also useful to expose `tol` and `max_iter`. 
Also, why not scaling values before? I think it would dramatically improve convergence

**Comment by lila167** [comment]
check it out now.
What values do you want to scale?

**Comment by giovp** [comment]
was thinking of both X and Y, standardized. Does it make sense?

**Comment by lila167** [comment]
You mean for regression? bulk samples don't need to be normalized (only TPM) but predictors are usually normalized (like CPM) before passing them to the tool.

**Comment by giovp** [comment]
is the normalization done internally or not? or do we need to log1p before input to autogenes
?

**Comment by lila167** [comment]
You should not log1p usually. The linear regression will be affected otherwise. The preprocessing of reference data like normalization is not part of the tool. We decided to leave that to the users :)
