### ISSUE TITLE
How is the cell type information being inputted into the regression model?

### ISSUE THREAD

**Issue by dst53** [theislab/AutoGeneS#7]
Hello,

Thank you for creating such a useful tool. After reading the preprint and examining the code for the deconvolve function I'm still unsure of how AutoGeneS is leveraging the user inputted cell types to produce the regression coefficients/estimated proportions. 

In the case of the nnls or nusvr model it looks to me like the inputs are X (bulk sample by gene expression matrix subsetted to n genes selected as solution to genetic algorithm) to predict y (vector of those n gene names). The function returns the coefficient estimates from the fitted model in a bulk sample by cell type matrix. 

How is the cell type information being inputted into the regression model?

**Comment by lila167** [comment]
Hi!

Thanks for using our tool!
The regression model uses the same reference that is given to the tool via "init". There you specify the cell types with "celltype_key". For regression, it uses the same annotations.
