### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by ThomasThaewel** [theislab/AutoGeneS#9]
Dear Theis lab,
thanks for this amazing tool to deconvolute bulk data. However I was wondering (maybe I missed it in the documentation) what kind of expression data you would suggest to use as input for the bulk data. We were trying basemean expression from deseq with mixed results. Also how many genes would you suggest to use when working with highly variable genes only ?
Thank you so much

**Comment by lila167** [comment]
Hi,

Thank you very much for your interest in our tool. 
In our paper, we used counts-per-million normalization. I would suggest to first filter the common genes between your single cell (or your reference) and bulk data and then normalize both. Also, log transformation is not recommended. 
I also usually use 5k-6k highly variable genes and select 300/400/500 informative genes using autogenes. You can then check which set of genes works the best for your data.

**Comment by ThomasThaewel** [comment]
Perfect that helps me out a lot!
Thank you so much

**Comment by lila167** [comment]
Happy to hear :)
